[package]
name = "netsec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
ping-rs = "0.1.2"
pinger = "1.1.0"
pnet = "0.34.0"
